name: BrainBytes Lint

on:
  push:
    branches: [ main, development, github-actions ]
  pull_request:
    branches: [ main, development, github-actions ]

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint frontend code
        working-directory: ./frontend
        run: npm run lint

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Lint backend code
        working-directory: ./backend
        run: npm run lint